FROM 32bit/ubuntu:14.04

RUN apt-get update && apt-get install -y python-software-properties software-properties-common git
RUN add-apt-repository ppa:evarlast/golang1.4
RUN apt-get update && apt-get install -y golang-go

ENV GOPATH=/root/go
RUN mkdir -p /root/go/src/github.com/influxdb/influxdb

VOLUME /root/go/src/github.com/influxdb/influxdb
